name: Actions CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@inkohx'
    - name: npm install and lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
